### ISSUE TITLE
CTAN's document collapses

### ISSUE THREAD

**Issue by e-kwsm** [urdh/skmath#28]
http://mirrors.ctan.org/macros/latex/contrib/skmath/skmath.pdf

For example,

![skmath_p3](https://user-images.githubusercontent.com/11627708/49864821-abe6de00-fe46-11e8-882d-664d0af2749c.png)

while [github's](https://github.com/urdh/skmath/blob/bafee33005a2adcc6803cae9a5236ecd7781b607/skmath.pdf) seems OK.

**Comment by urdh** [comment]
Should be fixed by the 0.5 release. If it's still broken when that has made it out to the CTAN mirrors, feel free to re-open the issue.

**Comment by e-kwsm** [comment]
Thanks.
